// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO_Rpnx8jbAUpHfZDm8PSbITMvyttb82s',
    appId: '1:929727902574:web:300080a103a017e3b4c77f',
    messagingSenderId: '929727902574',
    projectId: 'fortuna-b83b6',
    authDomain: 'fortuna-b83b6.firebaseapp.com',
    storageBucket: 'fortuna-b83b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBotCG5llRvYl8Fv0TBrFro3evWByxK5Wg',
    appId: '1:929727902574:android:495eeb53297528dab4c77f',
    messagingSenderId: '929727902574',
    projectId: 'fortuna-b83b6',
    storageBucket: 'fortuna-b83b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV7OVoZyDatsEI2uEZPWjQtlzPn7SIk-8',
    appId: '1:929727902574:ios:92959f827ef42844b4c77f',
    messagingSenderId: '929727902574',
    projectId: 'fortuna-b83b6',
    storageBucket: 'fortuna-b83b6.appspot.com',
    androidClientId: '929727902574-ar8j0pv90de3vn54jesvfucqbmcdskd1.apps.googleusercontent.com',
    iosClientId: '929727902574-i8dda43cji74aei22to2ukamo7tfc19o.apps.googleusercontent.com',
    iosBundleId: 'com.PODO.fortuna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV7OVoZyDatsEI2uEZPWjQtlzPn7SIk-8',
    appId: '1:929727902574:ios:6bbb265e7d881c4db4c77f',
    messagingSenderId: '929727902574',
    projectId: 'fortuna-b83b6',
    storageBucket: 'fortuna-b83b6.appspot.com',
    androidClientId: '929727902574-ar8j0pv90de3vn54jesvfucqbmcdskd1.apps.googleusercontent.com',
    iosClientId: '929727902574-eu6sbnlb11j37umgn49rvsrfou9sfrt5.apps.googleusercontent.com',
    iosBundleId: 'com.PODO.fortuna.RunnerTests',
  );
}
